### PR TITLE
feat: add hacky custom ddlparse logic for spanner.

### PR DESCRIPTION
**Pull request by rsyi**
Helps with https://github.com/dataframehq/whale/issues/68.

Tested the logic locally against some mock DDL statements (in a pretty hacky way), but hopefully it's useful. :)

### CODE REVIEW

**Comment by manuelzander** [comment]
Thanks @rsyi - played around with it locally and seems to help. We actually only need this:
```
def format_spanner_fields(column_name, column_contents):
    col = OrderedDict()
    col["name"] = column_name
    col["type"] = type = column_contents._data_type
    col["mode"] = column_contents.bigquery_mode
    return json.loads(json.dumps(col, ensure_ascii=False))
```

Unfortunately, there is another issue with the `DdlParse` instance, in particular `_CREATE_TABLE_STATEMENT` needs to be adapted for Spanner (we saw issues when DDLs use `[]` for arrays, e.g. `BOOL[]`, whereas Spanner uses something like `ARRAY<BOOL>`, but also for lengths indicated as string, for example `BYTES(MAX)`)

I managed to solve the array issue by using `Optional(Regex(r"\<(.*?)\>"))("array_brackets")` within `_CREATE_TABLE_STATEMENT`, and I suspect the `BYTES(MAX)` issue can be fixed by changing `Regex(r"[\d\*]+\s*,*\s*\d*")("length")` to a regex which allows chars/a string to be inside the (...). Any idea how to do this? I'm not too familiar with parsers/regex 😃

Btw I'm testing with this DDL:
```
CREATE TABLE ManuelsTable (
  col1 INT64,
  col2 STRING(MAX),
  col3 TIMESTAMP,
  col4 DATE,
  col5 BYTES(MAX),
  col6 ARRAY<BOOL>,
  col7 BOOL,
  col8 FLOAT64,
  col9 NUMERIC,
) PRIMARY KEY(col1) 
```

**Comment by biomunky** [comment]
Are we worried anti using the GCP client libraries to do this? I think there's a potentially easier way to go about it that should also pave the way to getting tags. Note that it does involve some SQL 🤮

**Comment by rsyi** [comment]
Ah @biomunky ! You're right -- it turns out you can get the type from `information_schema.columns` -- the field is just called `spanner_type`, so I missed it the first time around.

I wonder why they did this, instead of adhering to the ANSI standard...
image

Let's go with that. I'll re-open my old PR and tag you guys for review. :)

**Comment by rsyi** [comment]
Oh I forgot to mention -- @manuelzander, you should also feel free to take the PR as an example and just continue modifying this branch. I don't have the ability to really test against edge cases/understand the patterns that you guys want to use this for, so your thoughts would be greatly appreciated.

**Comment by manuelzander** [comment]
@rsyi Feel free to use this for https://github.com/dataframehq/whale/pull/69 😊

**Pull request closed without merging**
